'use strict';

const Homey                     = require('homey');
const TuyAPI                    = require('../../lib/SafeTuyAPI');
const { setupCloudLookup }      = require('../../lib/pairCloudLookup');
const { describeConnectFailure } = require('../../lib/connectFailure');
const { detectProtocolVersion } = require('../../lib/autoDetect');
const { scanNetwork }           = require('../../lib/networkScan');
const { detectViaCloud, guessedDefaults }        = require('../../lib/dpCodeMap');

// Maps this driver's settings keys to the Tuya cloud "code" names for the
// qccdz (EV charger) category. See lib/dpCodeMap.js.
const CLOUD_CODE_MAP = {
  dp_switch:           ['switch'],
  dp_work_state:       ['work_state'],
  dp_charge_current:   ['charge_cur_set'],
  dp_phase_a:          ['phase_a', 'phase_1'],
  dp_phase_b:          ['phase_b', 'phase_2'],
  dp_phase_c:          ['phase_c', 'phase_3'],
  dp_power_total:      ['power_total', 'cur_power'],
  dp_energy_total:     ['forward_energy_total'],
  dp_session_energy:   ['charge_energy_once'],
  dp_fault:            ['fault'],
  dp_connection_state: ['connection_state'],
  dp_work_mode:        ['work_mode'],
  dp_temperature:      ['temp_current'],
  dp_timer_on:         ['timer_on'],
  dp_live_updates:     ['online_state'],
  dp_clear_energy:     ['clear_energy', 'energy_clear'],
};

const WORK_STATES = [
  'charger_free', 'charger_insert', 'charger_free_fault', 'charger_wait',
  'charger_charging', 'charger_pause', 'charger_end', 'charger_fault',
];

class EvChargerDriver extends Homey.Driver {
  async onInit() {
    this.log('EV Charger driver initialized');

    // ── Trigger run-listeners ───────────────────────────────────────────────
    this.homey.flow.getDeviceTriggerCard('ev_state_changed')
      .registerRunListener(async () => true); // always fire; tokens carry the state

    // ── Conditions ──────────────────────────────────────────────────────────
    // "Is charging" is generated by Homey from the evcharger_charging
    // capability, so only the extras live here.
    this.homey.flow.getConditionCard('ev_device_is_connected')
      .registerRunListener(async (args) => args.device._conn?.connected === true);

    // Compares the raw Tuya work_state, which is finer-grained than Homey's
    // standard evcharger_charging_state. Read straight from the DPS cache.
    this.homey.flow.getConditionCard('ev_state_is')
      .registerRunListener(async (args) => {
        const dp = args.device.getSetting('dp_work_state');
        if (!dp || dp <= 0) return false;
        return String(args.device._lastDps?.[String(dp)] ?? '') === args.state;
      });

    // ── Actions ─────────────────────────────────────────────────────────────
    // Convenience card for users who think in amps — the charger's own unit.
    // Homey's built-in "Set target power" card covers the same DP in watts.
    this.homey.flow.getActionCard('ev_set_current')
      .registerRunListener(async (args) => {
        if (!args.device.hasCapability('target_power')) return;
        const min   = args.device.getSetting('current_min') ?? 6;
        const max   = args.device.getSetting('current_max') ?? 16;
        const amps  = Math.round(Math.max(min, Math.min(max, args.current)));
        const watts = amps * args.device._wattsPerAmp();
        await args.device.setCapabilityValue('target_power', watts);
        return args.device.triggerCapabilityListener('target_power', watts);
      });

    this.homey.flow.getActionCard('ev_reset_energy')
      .registerRunListener(async (args) => args.device.resetEnergy());

    this.homey.flow.getActionCard('ev_force_reconnect')
      .registerRunListener(async (args) => args.device.forceReconnect());

    this.homey.flow.getActionCard('ev_refresh_device')
      .registerRunListener(async (args) => args.device.pollNow());
  }

  // Which scaling setting belongs to which data point — see findScaleMismatch() in
  // app.js. Note these three offer fewer options than the plug's: a specification
  // asking for a divisor the dropdown does not list is reported, not written.
  getScaleMaps() {
    return {
      dp_charge_current: 'current_scale',
      dp_session_energy: 'session_energy_scale',
      dp_energy_total:   'total_energy_scale',
    };
  }

  async onPair(session) {
    setupCloudLookup(session, this.homey, this);
    let pendingDevice = null;
    let pendingRawDps = {};

    session.setHandler('scan_network', async () => scanNetwork(this.homey));

    session.setHandler('credentials', async (data) => {
      const { ip, deviceId, localKey, version } = data;

      const net = require('net');
      if (!net.isIPv4(ip)) throw new Error(this.homey.__('pair.credentials.invalidIp'));
      if (localKey.length !== 16 && localKey.length !== 32)
        throw new Error(this.homey.__('pair.credentials.invalidKey'));

      let connected      = false;
      let failureError = '';
      let detectedDps    = null;
      let actualVersion  = String(version);
      const collectedDps = {};
      let pairingDevice  = null;

      try {
        let rawDps;
        if (version === 'auto') {
          const result = await detectProtocolVersion({ ip, deviceId, localKey });
          actualVersion = result.version;
          rawDps        = result.dps;
        } else {
          const device = new TuyAPI({ id: deviceId, key: localKey, ip, version: actualVersion, issueGetOnConnect: true });
          pairingDevice = device;
          device.on('error', () => {});
          const tmpDps = {};
          device.on('data', (payload) => { if (payload?.dps) Object.assign(tmpDps, payload.dps); });
          // Replies to a DP_REFRESH request arrive on a separate event; some devices
          // report the packed voltage/current/power DP only that way.
          device.on('dp-refresh', (payload) => { if (payload?.dps) Object.assign(tmpDps, payload.dps); });
          await Promise.race([
            device.connect(),
            new Promise((_, rej) => setTimeout(() => rej(new Error('Connection timed out')), 8000)),
          ]);
          await new Promise((resolve) => setTimeout(resolve, 2000));
          // Always ask for a refresh, not just when nothing arrived: devices that do
          // answer dp_query may still withhold the refresh-only DPs, which is where
          // packed voltage/current/power values usually live.
          try { device.refresh(); } catch (_) {}
          await new Promise((resolve) => setTimeout(resolve, 2000));
          device.disconnect();
          pairingDevice = null;
          rawDps = tmpDps;
        }
        Object.assign(collectedDps, rawDps);
        connected = true;
        if (Object.keys(collectedDps).length > 0) {
          detectedDps = this._detectDps(collectedDps);
          this.log('Locally detected DPs (value heuristic):', JSON.stringify(detectedDps));

          const cloudDps = await detectViaCloud(this.homey, deviceId, CLOUD_CODE_MAP, (m) => this.log(m), {}, guessedDefaults(detectedDps, collectedDps));
          if (Object.keys(cloudDps).length > 0) {
            Object.assign(detectedDps, cloudDps);
            this.log('Final detected DPs (cloud-refined):', JSON.stringify(detectedDps));
          }
        }
      } catch (err) {
        connected = false;
        failureError = err.message;
        try { if (pairingDevice) pairingDevice.disconnect(); } catch (_e) {}
        this.log('Connection test failed:', err.message);
      }

      pendingDevice = {
        name: this.homey.__('device.defaultName.ev_charger'),
        data: { id: deviceId },
        settings: {
          ip, device_id: deviceId, local_key: localKey, version: actualVersion,
          ...(detectedDps || {}),
        },
      };
      pendingRawDps = collectedDps;
      // The dialog used to say only "connection failed" — the same sentence
      // whether the address is wrong, the key is wrong, or the device does not
      // offer local control at all. So people work through the one visible
      // choice, the protocol version. Looking at port 6668 separates the cases.
      const failureHint = connected
        ? ''
        : await describeConnectFailure({ ip, error: failureError });
      if (failureHint) this.log(failureHint);

      return { connected, detectedVersion: actualVersion, detectedDps, failureHint };
    });

    session.setHandler('list_devices', async () => pendingDevice ? [pendingDevice] : []);
    session.setHandler('raw_dps',      async () => pendingRawDps || {});
    session.setHandler('set_device_name', async (name) => {
      if (pendingDevice && name?.trim()) pendingDevice.name = name.trim();
    });
  }

  /**
   * Auto-detect DP mapping from a raw DPS snapshot.
   *
   * Defaults follow the qccdz layout shared by all 37 EV-charger configs in
   * make-all/tuya-local. Optional DPs that only some models expose (phases B/C,
   * total power, lifetime counter, live-updates switch) start at 0 and are
   * enabled only when actually observed in the snapshot, so single-phase units
   * don't end up with dead phase-B/C tiles.
   */
  _detectDps(dps) {
    const result = {
      dp_switch:           18,
      dp_work_state:       3,
      dp_charge_current:   4,
      // DP 6 is near-universal on this category but is often reported only in
      // reply to a DP_REFRESH request, so it may be absent from a plain query.
      // The pairing snapshot now includes such replies; the presence check below
      // still clears it for the few models that genuinely never send it.
      dp_phase_a:          6,
      dp_phase_b:          0,
      dp_phase_c:          0,
      dp_power_total:      0,
      dp_energy_total:     0,
      // DP 1 is the counter that rises while charging on these units, despite
      // being named "forward_energy_total". DP 25 ("charge_energy_once") holds
      // the *previous* completed session and stays static during a charge, so
      // accumulating from it would never move. Verified against two live
      // snapshots four minutes apart and against tuya-local, which likewise
      // treats DP 1 as the energy sensor and DP 25 as "last charge".
      dp_session_energy:   1,
      dp_fault:            10,
      dp_connection_state: 13,
      dp_work_mode:        0,
      dp_temperature:      0,
      dp_timer_on:         0,
      dp_live_updates:     0,
      dp_clear_energy:     0,
      current_min:         6,
      current_max:         16,
      phase_count:         '1',
      nominal_voltage:     230,
      // Scales the vast majority of chargers use. A handful deviate (current ×10,
      // or whole kWh instead of hundredths) and cannot be told apart from a single
      // pairing snapshot, so these stay adjustable in device settings.
      current_scale:        '1',
      session_energy_scale: '0.01',
      total_energy_scale:   '0.01',
      // Integrating the live power reading is the more dependable default. The
      // charger's own session counter is exact when it works, but on several units
      // it never moves, or is scaled differently from the rest of the DPs, and the
      // symptom is a total that silently stays at zero or drifts — hard to tell
      // apart from a mapping mistake. This setting is ignored entirely on chargers
      // that report a lifetime total themselves, and a charger with no power DP
      // gets estimate_power switched on below, which the integration then uses.
      // Set here rather than as the manifest default so that chargers paired
      // earlier keep whatever they are on today.
      total_energy_source:        'power',
      // Chargers with no power DP get the estimate switched on, since otherwise
      // the power tile would stay permanently empty. Enabled below.
      estimate_power:       false,
    };

    const present = (dp) => Object.prototype.hasOwnProperty.call(dps, String(dp));

    for (const [dpStr, val] of Object.entries(dps)) {
      const dp = parseInt(dpStr, 10);

      if (typeof val === 'string') {
        // These three enums are unmistakable — match them wherever they sit.
        if (WORK_STATES.includes(val))       { result.dp_work_state = dp;       continue; }
        if (val.startsWith('controlpi_'))    { result.dp_connection_state = dp; continue; }
        if (val.startsWith('charge_'))       { result.dp_work_mode = dp;        continue; }
        if (val === 'online' || val === 'offline') { result.dp_live_updates = dp; continue; }
      }
    }

    // Optional DPs at their standard positions — enable only if the charger
    // actually reported them.
    // Clear phase A if the charger sent nothing for it even after the refresh
    // request, so the settings reflect what the device actually delivers and the
    // power estimate below can take over instead of leaving empty tiles.
    if (!present(6)) result.dp_phase_a      = 0;
    if (present(7))  result.dp_phase_b      = 7;
    if (present(8))  result.dp_phase_c      = 8;
    // Nothing reports power on this charger — estimate it from the current limit
    // so the power tile and the energy dashboard have something to work with.
    if (!present(6) && !present(9) && !present(5)) result.estimate_power = true;
    // Reporting phase B/C means a three-phase charger, which sets the watts-per-amp
    // factor used to convert Homey's target_power into the charger's current limit.
    if (present(7) && present(8)) result.phase_count = '3';
    if (present(9))  result.dp_power_total  = 9;   // total power, W
    else if (present(5)) result.dp_power_total = 5; // single-phase power, W
    if (present(24)) result.dp_temperature  = 24;
    if (present(28)) result.dp_timer_on     = 28;
    if (present(16)) result.dp_clear_energy = 16;

    // If DP 1 is absent but DP 25 exists, fall back to DP 25 as the counter —
    // some models only expose that one.
    if (!present(1) && present(25)) result.dp_session_energy = 25;

    // Lifetime counter (DP 1) is deliberately left disabled even when present.
    // Many chargers expose it with a plausible non-zero value that then never
    // changes over the local connection, so a single pairing snapshot cannot
    // tell a working counter from a frozen one — and guessing wrong silently
    // freezes the energy total. Accumulating from session energy (DP 25) works
    // on every model tested, so that is the default; users whose counter does
    // update can set dp_energy_total to 1 in device settings.

    return result;
  }

  async onPairListDevices() { return []; }
}

module.exports = EvChargerDriver;
